-- Works against a fresh database and each existing Alembic revision. No user data is dropped.
DO $$ BEGIN CREATE TYPE chat_type AS ENUM ('group','supergroup','channel'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE announcement_status AS ENUM ('active','paused','deleted'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE first_run_mode AS ENUM ('immediate','scheduled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE delivery_status AS ENUM ('sent','failed','rate_limited','skipped'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, telegram_id bigint UNIQUE NOT NULL,
 username varchar(255), first_name varchar(255), last_activity_at timestamptz NOT NULL DEFAULT now(),
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS groups (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id bigint UNIQUE NOT NULL,
 title varchar(255) NOT NULL, chat_type chat_type NOT NULL, bot_can_post boolean NOT NULL DEFAULT false,
 is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), verified_at timestamptz
);
CREATE TABLE IF NOT EXISTS user_groups (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 group_id bigint NOT NULL REFERENCES groups ON DELETE CASCADE, connected_by_telegram_id bigint NOT NULL,
 connected_at timestamptz NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true,
 CONSTRAINT uq_user_groups_user_group UNIQUE(user_id,group_id)
);
CREATE TABLE IF NOT EXISTS templates (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 text text NOT NULL, photo_file_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS announcements (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 text text NOT NULL, photo_file_id text, contact_phone varchar(32), contact_telegram varchar(255), contact_name varchar(255),
 interval_minutes integer NOT NULL CHECK (interval_minutes > 0), status announcement_status NOT NULL DEFAULT 'active',
 first_run_mode first_run_mode NOT NULL, next_run_at timestamptz, last_run_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS announcement_groups (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, announcement_id bigint NOT NULL REFERENCES announcements ON DELETE CASCADE,
 group_id bigint NOT NULL REFERENCES groups ON DELETE CASCADE, CONSTRAINT uq_announcement_groups UNIQUE(announcement_id,group_id)
);
CREATE TABLE IF NOT EXISTS delivery_logs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, announcement_id bigint NOT NULL REFERENCES announcements ON DELETE CASCADE,
 group_id bigint NOT NULL REFERENCES groups ON DELETE CASCADE, scheduled_at timestamptz NOT NULL, sent_at timestamptz,
 status delivery_status NOT NULL, telegram_message_id bigint, error_code varchar(128), error_message text,
 created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_delivery_logs_schedule_group UNIQUE(announcement_id,group_id,scheduled_at)
);
ALTER TABLE announcements DROP CONSTRAINT IF EXISTS ck_announcements_contact_required;
ALTER TABLE announcements ALTER COLUMN contact_phone DROP NOT NULL;
ALTER TABLE announcements ALTER COLUMN contact_telegram DROP NOT NULL;
ALTER TABLE announcements ALTER COLUMN contact_name DROP NOT NULL;
ALTER TABLE templates ADD COLUMN IF NOT EXISTS photo_file_ids json;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS photo_file_ids json;
ALTER TABLE delivery_logs ADD COLUMN IF NOT EXISTS telegram_message_ids json;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS slow_mode_delay integer NOT NULL DEFAULT 0;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS bot_is_admin boolean NOT NULL DEFAULT false;
ALTER TABLE user_groups ADD COLUMN IF NOT EXISTS can_post boolean NOT NULL DEFAULT false;
ALTER TABLE user_groups ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;
ALTER TABLE user_groups ADD COLUMN IF NOT EXISTS access_hash varchar(32);
ALTER TABLE user_groups ADD COLUMN IF NOT EXISTS retry_after timestamptz;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS delivery_cycle_at timestamptz;
ALTER TABLE delivery_logs ADD COLUMN IF NOT EXISTS sender_telegram_id bigint;
CREATE TABLE IF NOT EXISTS telegram_accounts (
 user_id bigint PRIMARY KEY REFERENCES users ON DELETE CASCADE, telegram_id bigint UNIQUE NOT NULL,
 encrypted_session text NOT NULL, retry_after timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS account_logins (
 token_hash varchar(64) PRIMARY KEY, user_id bigint UNIQUE NOT NULL REFERENCES users ON DELETE CASCADE,
 expires_at timestamptz NOT NULL, attempts integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS user_states (
 user_id bigint PRIMARY KEY REFERENCES users ON DELETE CASCADE, data jsonb NOT NULL DEFAULT '{}',
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS processed_updates (update_id bigint PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reply_notifications (
 user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE, chat_id bigint NOT NULL,
 message_id bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,chat_id,message_id)
);
CREATE INDEX IF NOT EXISTS ix_announcements_status_next_run_at ON announcements(status,next_run_at);
CREATE INDEX IF NOT EXISTS ix_delivery_logs_announcement_scheduled ON delivery_logs(announcement_id,scheduled_at);
CREATE INDEX IF NOT EXISTS ix_delivery_logs_sender_sent ON delivery_logs(sender_telegram_id,sent_at);
