ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_started_at timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS paid_until timestamptz;
-- Existing publishers receive a full trial from the upgrade; other users start at their first announcement.
UPDATE users u SET trial_started_at=now(),trial_ends_at=now()+interval '7 days'
 WHERE trial_started_at IS NULL AND EXISTS(SELECT 1 FROM announcements a WHERE a.user_id=u.id);
CREATE TABLE IF NOT EXISTS tariff_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 admin_telegram_id bigint NOT NULL, request_id uuid UNIQUE NOT NULL, action text NOT NULL CHECK(action IN ('activate','revoke')),
 amount_sum integer NOT NULL, previous_until timestamptz, paid_until timestamptz,
 note varchar(500) NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS support_messages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 direction text NOT NULL CHECK(direction IN ('in','out')), text text NOT NULL DEFAULT '',
 kind text NOT NULL DEFAULT 'text', file_id text, file_name text, telegram_message_id bigint,
 admin_telegram_id bigint, request_id uuid UNIQUE, delivery_status text NOT NULL DEFAULT 'received',
 error_code text, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(user_id,direction,telegram_message_id)
);
CREATE INDEX IF NOT EXISTS ix_support_user_created ON support_messages(user_id,id DESC);
CREATE INDEX IF NOT EXISTS ix_support_unread ON support_messages(user_id) WHERE direction='in' AND read_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_tariff_events_user ON tariff_events(user_id,id DESC);
