ALTER TABLE announcements ADD COLUMN IF NOT EXISTS pause_reason text;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS cycle_initialized boolean NOT NULL DEFAULT false;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS last_delivery_summary jsonb;
UPDATE announcements SET pause_reason='manual' WHERE status='paused' AND pause_reason IS NULL;

-- Short-lived accounting survives deletion of ads, logs and group connections.
-- No message text, photo identifiers, or foreign key to the deleted content.
CREATE TABLE IF NOT EXISTS delivery_usage (
 delivery_log_id bigint PRIMARY KEY, sender_telegram_id bigint NOT NULL,
 chat_id bigint NOT NULL, sent_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_delivery_usage_sender_time ON delivery_usage(sender_telegram_id,sent_at);
CREATE OR REPLACE FUNCTION record_delivery_usage() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.sent_at IS NOT NULL AND NEW.sender_telegram_id IS NOT NULL THEN
  INSERT INTO delivery_usage(delivery_log_id,sender_telegram_id,chat_id,sent_at)
   SELECT NEW.id,NEW.sender_telegram_id,g.chat_id,NEW.sent_at FROM groups g WHERE g.id=NEW.group_id
   ON CONFLICT(delivery_log_id) DO UPDATE SET sent_at=EXCLUDED.sent_at;
 END IF;
 RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS delivery_usage_recorded ON delivery_logs;
CREATE TRIGGER delivery_usage_recorded AFTER INSERT OR UPDATE OF sent_at ON delivery_logs
 FOR EACH ROW EXECUTE FUNCTION record_delivery_usage();
INSERT INTO delivery_usage(delivery_log_id,sender_telegram_id,chat_id,sent_at)
 SELECT l.id,l.sender_telegram_id,g.chat_id,l.sent_at FROM delivery_logs l JOIN groups g ON g.id=l.group_id
 WHERE l.sent_at>now()-interval '1 day' AND l.sender_telegram_id IS NOT NULL
 ON CONFLICT(delivery_log_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_notifications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
 dedup_key text UNIQUE NOT NULL, kind text NOT NULL, payload jsonb NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','failed','unknown','skipped')),
 available_at timestamptz NOT NULL DEFAULT now(), telegram_message_id bigint, error_code text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_user_notifications_pending ON user_notifications(available_at,id) WHERE status='pending';
